version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A src.celery_worker.celery_app worker --loglevel=info --queues=email
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
      - FRONTEND_URL
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data