version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A src.celery_worker.celery_app worker --loglevel=info --queues=email
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
      - FRONTEND_URL