"""create posts models

Revision ID: b72df41a9333
Revises: 3f1c822593e7
Create Date: 2025-08-26 16:43:33.936286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72df41a9333'
down_revision: Union[str, None] = '3f1c822593e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_user_created', 'posts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_table('post_comm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_comm_parent', 'post_comm', ['parent_id'], unique=False)
    op.create_index(op.f('ix_post_comm_parent_id'), 'post_comm', ['parent_id'], unique=False)
    op.create_index('ix_post_comm_post_created', 'post_comm', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_comm_post_id'), 'post_comm', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comm_user_id'), 'post_comm', ['user_id'], unique=False)
    op.create_table('post_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('position BETWEEN 1 AND 10', name='ck_post_images_position_1_10'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'position', name='uq_post_images_post_position')
    )
    op.create_index(op.f('ix_post_images_post_id'), 'post_images', ['post_id'], unique=False)
    op.create_index('ix_post_images_post_position', 'post_images', ['post_id', 'position'], unique=False)
    op.create_table('post_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_likes_post_user')
    )
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.create_index('ix_post_likes_user', 'post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_likes_user_id'), 'post_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_likes_user_id'), table_name='post_likes')
    op.drop_index('ix_post_likes_user', table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index('ix_post_images_post_position', table_name='post_images')
    op.drop_index(op.f('ix_post_images_post_id'), table_name='post_images')
    op.drop_table('post_images')
    op.drop_index(op.f('ix_post_comm_user_id'), table_name='post_comm')
    op.drop_index(op.f('ix_post_comm_post_id'), table_name='post_comm')
    op.drop_index('ix_post_comm_post_created', table_name='post_comm')
    op.drop_index(op.f('ix_post_comm_parent_id'), table_name='post_comm')
    op.drop_index('ix_post_comm_parent', table_name='post_comm')
    op.drop_table('post_comm')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index('ix_posts_user_created', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
